### ISSUE TITLE
Jupyter kernel

### ISSUE THREAD

**Issue by anticdimi** [mwidjaja1/DSOnMacARM#1]
Hey, it's not really an issue, I just came across this PR https://github.com/ipython/ipykernel/pull/561, seems like the guy fixed the jupyter to run properly. It would be nice of you if you check whether it's working properly, so we all know! 
You should check it out, and keep this repo running it's really a fortune to read all of this before buying a new MacBook! Thanks! :)

**Comment by mwidjaja1** [comment]
It works for me! I'll add this tip to my Notes for now, with the caveat that in theory, it would probably be checked into master (one would hope).

Thanks for the share!
