### ISSUE TITLE
R and compiling packages architecture problem

### ISSUE THREAD

**Issue by jebyrnes** [mwidjaja1/DSOnMacARM#8]
I've installed the version of R for arm64 from https://mac.r-project.org/ but - when I try and install packages that require compilation, I get

```
 building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

Thoughts on how to resolve this?

For example

```
ld: warning: ignoring file /usr/local/opt/llvm/lib/libc++.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: in '/usr/local/opt/llvm/lib/libunwind.dylib', building for macOS-arm64 but attempting to link with file built for macOS-x86_64
```

**Comment by jebyrnes** [comment]
(For amusement, this is a real problem, as I'm trying to put up a post in blogdown about how to get R tensorflow to work on an m1.....but xfun requires compilation)

**Comment by mwidjaja1** [comment]
Oh man I actually don't use R personally in my life... or actually know how to code (well) in R. But I do know there are issues in general building R on Macs. I thought those issues though were related to Fortran, not so much C++.

**Comment by jebyrnes** [comment]
OK.
So.
It looks like I'm an idiot, and it was old .R/Makevars that I'd used previously to deal with some compiler issues on an x86 mac. Once I removed the file, everything went swimmingly. And so far - things are really fast. My brms runs have been blazing.
