### ISSUE TITLE
Keras

### ISSUE THREAD

**Issue by Benjiini** [mwidjaja1/DSOnMacARM#9]
Hey, 
I was wondering, if you are using Keras. 
Maybe, an addition would be nice ;)
Thanks in advance

**Comment by mwidjaja1** [comment]
I unfortunately do not use Keras in a long while, but I have heard of issues in that area.

**Comment by jebyrnes** [comment]
See this post - it's for R, but leading up to the R part is what you need to get keras and tensorflow to run in python. http://www.imachordata.com/2021/05/07/r-tensorflow-on-an-m1-mac-without-crashing/

**Comment by Benjiini** [comment]
Thanks a lot for the links. 
I did some research as well and noticed, that Keras (at least all code, that I use)  ist available by using `from Tensorflow import keras`  which was crazy fast compared to my old MBP
So there was no need for further action. (at least for me :) )
